project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: /packages/core/src/locales/en-US/*.po
    translation: /packages/core/src/locales/%locale%/messages.po
  - source: /packages/gui/src/locales/en-US/*.po
    translation: /packages/gui/src/locales/%locale%/messages.po
  - source: /packages/wallets/src/locales/en-US/*.po
    translation: /packages/wallets/src/locales/%locale%/messages.po
