project_id: 1
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
base_url: "https://chia.crowdin.com"
preserve_hierarchy: true
files:
  - source: /packages/core/src/locales/en-US/*.po
    translation: /packages/core/src/locales/%locale%/messages.po
  - source: /packages/gui/src/locales/en-US/*.po
    translation: /packages/gui/src/locales/%locale%/messages.po
  - source: /packages/wallets/src/locales/en-US/*.po
    translation: /packages/wallets/src/locales/%locale%/messages.po
