enum TransactionType {
  INCOMING = 0,
  OUTGOING = 1,
  COINBASE_REWARD = 2,
  FEE_REWARD = 3,
  INCOMING_TRADE = 4,
  OUTGOING_TRADE = 5,
  INCOMING_CLAWBACK_RECEIVE = 6,
  INCOMING_CLAWBACK_SEND = 7,
  OUTGOING_CLAWBACK = 8,
  INCOMING_CRCAT_PENDING = 9,
}

export default TransactionType;
