enum ErrorCode {
  NO_FILE_AVAILABLE,
  INVALID_PREVIEW_URL,
  UPDATE_PENDING,
  HASH_MISMATCH,
  IMAGE_HASH_MISMATCH,
  VIDEO_HASH_MISMATCH,
  METADATA_HASH_MISMATCH,
  MISSING_PREVIEW_VIDEO_HASH,
  MISSING_PREVIEW_IMAGE_HASH,
  FAILED_FETCH_CONTENT,
  INVALID_METADATA_URL,
  ERROR_PARSING_JSON,
  RESPONSE_TOO_LARGE,
}

export default ErrorCode;
