name: Push strings to Crowdin

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  push-to-crowdin:
    runs-on: [k8s-public]
    container: node:18
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vault Login
        uses: Chia-Network/actions/vault/login@main
        with:
          vault_url: ${{ secrets.VAULT_URL }}
          role_name: github-chia-blockchain-gui

      - name: Get secrets from vault
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ env.VAULT_TOKEN }}
          secrets: |
            secret/data/crowdin token | CROWDIN_PERSONAL_TOKEN;
            secret/data/crowdin project-id-blockchain-gui | CROWDIN_PROJECT_ID;

      - name: crowdin action
        uses: crowdin/github-action@v2.2.0
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          crowdin_branch_name: ${{ github.ref_name }} # The "branch" (folder) in crowdin to source from. Match the branch name in GH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
