name: Extract and compile locales
on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches-ignore:
      - 'main'

jobs:
  run:
    name: locales
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Update source code
        run: |
          lingui extract
          lingui compile

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Locale bot
          author_email: bot@chia.net
          message: 'Compiled locales'
          add: './src/locales'
